### ISSUE TITLE
https://doc.lizejun.fit/home/l/.config/Typora/typora-user-images/image-20221223001029503.png

### ISSUE THREAD

**Issue by LIZEJU** [LIZEJU/hexo_blog#4]
```
https://doc.lizejun.fit/home/l/.config/Typora/typora-user-images/image-20221223001029503.png
```

**Comment by LIZEJU** [comment]
throw err;
    ^

Error: ENOENT: no such file or directory, open
    at Object.openSync (node:fs:584:3)
    at Object.readFileSync (node:fs:452:35)
    at write_file_lzj (/home/l/桌面/clear/node_modules/hexo-absolute/lib/filter.js:31:21)
    at /home/l/桌面/clear/node_modules/hexo-absolute/lib/filter.js:188:20
    at FSReqCallback.oncomplete (node:fs:180:23) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}

**Comment by LIZEJU** [comment]
// fs.access(path, fs.constants.F_OK | fs.constants.W_OK, (err) => {
        //   if (err) {
        //     console.error(
        //       `${path} ${err.code === 'ENOENT' ? '不存在' : '只可读'}`);
        //   } else {
        //     console.log(`${path} 存在，且可写`);
           
        //     console.log(' 存在，且可写8'+path);
        //     // tmp=path;
        //     ans = host + path.replace('/', '');
        //     console.log("path2---->"+ans);
        //   }
        // });
这个方法access就不走外面
